### ISSUE TITLE
Program type already present: android.support.v4.app.LoaderManager Message{kind=ERROR, text=Program type already present: android.support.v4.app.LoaderManager, sources=[Unknown source file], tool name=Optional.of(D8)}

### ISSUE THREAD

**Issue by Mateeen** [mattprecious/swirl#13]

**Comment by JakeWharton** [comment]
This is not a problem with the library but a problem with your build configuration. The most common cause nowadays is that you are including both androidx and android.support versions of the support libraries in your build. You can use the `dependencies` task to try and narrow down where this comes from. In order to mix these dependencies you will have to enable jetifier / dejetifier as well.
